#!/usr/bin/env python3
import os
import rospy
from std_msgs.msg import String
from sensor_msgs.msg import Image
from vision_msgs.msg import Detection2D, Detection2DArray, ObjectHypothesisWithPose
from detector import Detector
import ros_numpy # pip3 install git+https://github.com/eric-wieser/ros_numpy
import cv2
import numpy as np
from keras_vggface.vggface import VGGFace
from keras_vggface.utils import preprocess_input
from scipy.spatial.distance import cosine
import pickle

def getFaceBox(net, frame, conf_threshold=0.8):
    frameOpencvDnn = frame.copy()
    frameHeight = frameOpencvDnn.shape[0]
    frameWidth = frameOpencvDnn.shape[1]
    
    #swapRB =True
    # flag which indicates that swap first and last channels in 3-channel image is necessary.
    #crop = False
    # flag which indicates whether image will be cropped after resize or not
    # If crop is false, direct resize without cropping and preserving aspect ratio is performed
    blob = cv2.dnn.blobFromImage(frameOpencvDnn, 1.0, (300, 300), [104, 117, 123], True, False)

    net.setInput(blob)
    detections = net.forward()
    bboxes = []
    for i in range(detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        if confidence > conf_threshold and detections[0, 0, i, 5]<1 and detections[0, 0, i, 6]<1:
            x1 = int(detections[0, 0, i, 3] * frameWidth)
            y1 = int(detections[0, 0, i, 4] * frameHeight)
            x2 = int(detections[0, 0, i, 5] * frameWidth)
            y2 = int(detections[0, 0, i, 6] * frameHeight)
            bboxes.append([x1, y1, x2, y2])
            #cv2.rectangle(frameOpencvDnn, (x1, y1), (x2, y2), (0, 255, 0), int(round(frameHeight/300)), 8)
    return frameOpencvDnn, bboxes

def data_from_file(name):
    with open(name, 'rb') as handle:
        X = pickle.load(handle)
    return X
# Initialize face detector
faceProto = os.path.join(os.path.dirname(__file__),"opencv_face_detector.pbtxt")
faceModel = os.path.join(os.path.dirname(__file__),"opencv_face_detector_uint8.pb")
print(faceProto,faceModel)
faceNet = cv2.dnn.readNet(faceModel, faceProto)

# Load the VGG-Face model based on ResNet-50
face_reco_model = VGGFace(model='resnet50', include_top=False, pooling='avg')

padding = 0.2
INPUT_SIZE = (224,224)
rejection_threshold=0.4

datapath = os.path.join(os.path.dirname(__file__),"data.pickle")
database = data_from_file(datapath)
rospy.init_node('detector_node')

pub = rospy.Publisher('detection', Detection2DArray, queue_size=2)
pub_audio= rospy.Publisher('ID',String,queue_size=10)

def rcv_image(msg):
    image = ros_numpy.numpify(msg)
    frameFace, bboxes = getFaceBox(faceNet, image)     # Get face
    message = Detection2DArray()

    for i,bbox in enumerate(bboxes):
        d = Detection2D()

        # bbox cordinates
        w = bbox[2]-bbox[0]
        h = bbox[3]-bbox[1]
        d.bbox.size_x = w
        d.bbox.size_y = h
        d.bbox.center.x = bbox[0]+w/2
        d.bbox.center.y = bbox[1]+h/2

        # identity prediction
        padding_px = int(padding*max(h,w))
        face = image[max(0,bbox[1]-padding_px):min(bbox[3]+padding_px,image.shape[0]-1),max(0,bbox[0]-padding_px):min(bbox[2]+padding_px, image.shape[1]-1)]
        face = face[ face.shape[0]//2 - face.shape[1]//2 : face.shape[0]//2 + face.shape[1]//2, :, :]
        # Preprocess image
        resized_face = cv2.resize(face,INPUT_SIZE)
        ##
        faceim = preprocess_input([resized_face.astype(np.float32)], version=2)
        feature_vector = (face_reco_model.predict(faceim,verbose='false')).flatten()
        min_distance = ["unknown", 1000000000000]
        for person in database:
            for face in person:
                distance = cosine(feature_vector, face['feature_vector'])
                if distance < min_distance[1] and distance < rejection_threshold:
                    min_distance[0] = face['id']
                    min_distance[1] = distance
        d.source_img.header.frame_id = min_distance[0]
        message.detections.append(d)

    pub.publish(message)
    if len(bboxes) > 0:
        pub_audio.publish(min_distance[0])
    else:
        pub_audio.publish("NO")
    rospy.loginfo("published")


si = rospy.Subscriber("webcam", Image, rcv_image)



try:
    rospy.spin()

except KeyboardInterrupt:
    print("Shutting down")
    
