// Generated by gencpp from file rasa_ros/Rest.msg
// DO NOT EDIT!


#ifndef RASA_ROS_MESSAGE_REST_H
#define RASA_ROS_MESSAGE_REST_H

#include <ros/service_traits.h>


#include <rasa_ros/RestRequest.h>
#include <rasa_ros/RestResponse.h>


namespace rasa_ros
{

struct Rest
{

typedef RestRequest Request;
typedef RestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Rest
} // namespace rasa_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rasa_ros::Rest > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::rasa_ros::Rest&) { return value(); }
};

template<>
struct DataType< ::rasa_ros::Rest > {
  static const char* value()
  {
    return "rasa_ros/Rest";
  }

  static const char* value(const ::rasa_ros::Rest&) { return value(); }
};


// service_traits::MD5Sum< ::rasa_ros::RestRequest> should match
// service_traits::MD5Sum< ::rasa_ros::Rest >
template<>
struct MD5Sum< ::rasa_ros::RestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rasa_ros::Rest >::value();
  }
  static const char* value(const ::rasa_ros::RestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasa_ros::RestRequest> should match
// service_traits::DataType< ::rasa_ros::Rest >
template<>
struct DataType< ::rasa_ros::RestRequest>
{
  static const char* value()
  {
    return DataType< ::rasa_ros::Rest >::value();
  }
  static const char* value(const ::rasa_ros::RestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rasa_ros::RestResponse> should match
// service_traits::MD5Sum< ::rasa_ros::Rest >
template<>
struct MD5Sum< ::rasa_ros::RestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rasa_ros::Rest >::value();
  }
  static const char* value(const ::rasa_ros::RestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasa_ros::RestResponse> should match
// service_traits::DataType< ::rasa_ros::Rest >
template<>
struct DataType< ::rasa_ros::RestResponse>
{
  static const char* value()
  {
    return DataType< ::rasa_ros::Rest >::value();
  }
  static const char* value(const ::rasa_ros::RestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASA_ROS_MESSAGE_REST_H
