// Generated by gencpp from file rasa_ros/WakeUp.msg
// DO NOT EDIT!


#ifndef RASA_ROS_MESSAGE_WAKEUP_H
#define RASA_ROS_MESSAGE_WAKEUP_H

#include <ros/service_traits.h>


#include <rasa_ros/WakeUpRequest.h>
#include <rasa_ros/WakeUpResponse.h>


namespace rasa_ros
{

struct WakeUp
{

typedef WakeUpRequest Request;
typedef WakeUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WakeUp
} // namespace rasa_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rasa_ros::WakeUp > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::rasa_ros::WakeUp&) { return value(); }
};

template<>
struct DataType< ::rasa_ros::WakeUp > {
  static const char* value()
  {
    return "rasa_ros/WakeUp";
  }

  static const char* value(const ::rasa_ros::WakeUp&) { return value(); }
};


// service_traits::MD5Sum< ::rasa_ros::WakeUpRequest> should match
// service_traits::MD5Sum< ::rasa_ros::WakeUp >
template<>
struct MD5Sum< ::rasa_ros::WakeUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rasa_ros::WakeUp >::value();
  }
  static const char* value(const ::rasa_ros::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasa_ros::WakeUpRequest> should match
// service_traits::DataType< ::rasa_ros::WakeUp >
template<>
struct DataType< ::rasa_ros::WakeUpRequest>
{
  static const char* value()
  {
    return DataType< ::rasa_ros::WakeUp >::value();
  }
  static const char* value(const ::rasa_ros::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rasa_ros::WakeUpResponse> should match
// service_traits::MD5Sum< ::rasa_ros::WakeUp >
template<>
struct MD5Sum< ::rasa_ros::WakeUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rasa_ros::WakeUp >::value();
  }
  static const char* value(const ::rasa_ros::WakeUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasa_ros::WakeUpResponse> should match
// service_traits::DataType< ::rasa_ros::WakeUp >
template<>
struct DataType< ::rasa_ros::WakeUpResponse>
{
  static const char* value()
  {
    return DataType< ::rasa_ros::WakeUp >::value();
  }
  static const char* value(const ::rasa_ros::WakeUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASA_ROS_MESSAGE_WAKEUP_H
